#program to show sequence of numbers generated by given list of range expressions
# 1. range(5)
print("Sequence of numbers in range(5)")
for i in range(5):
    print(i,end=' ')
# 2. range(3,10)
print("\nSequence of numbers in range(3,10)")
for i in range(3,10):
    print(i,end=' ')
# 3. range(4,13,3)
print("\nSequence of numbers in range (4,13,3)")
for i in range(4,13,3):
    print(i,end=' ')
# 4. range(15,5,-2)
print("\nSequence of numbers in range (15,5,-2)")
for i in range(15,5,-2):
    print(i,end=' ')
# 5. range(5,3)
print("\nSequence of numbers in range (5,3)")
for i in range(5,3):
    print(i,end=' ')
